-- MySQL Script generated by MySQL Workbench
-- Fri Mar 11 16:41:18 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gcpnext16lamp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gcpnext16lamp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gcpnext16lamp` DEFAULT CHARACTER SET utf8 ;
USE `gcpnext16lamp` ;

-- -----------------------------------------------------
-- Table `gcpnext16lamp`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gcpnext16lamp`.`user` (
  `id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `roles` VARCHAR(45) NULL,
  `token` VARCHAR(100) NULL,
  `expiration_time` DATETIME NULL,
  `is_admin` INT NOT NULL,
  `created_at` DATETIME NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `gcpnext16lamp`.`gallery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gcpnext16lamp`.`gallery` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(250) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `gcpnext16lamp`.`meme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gcpnext16lamp`.`meme` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `top_text` VARCHAR(200) NULL,
  `bottom_text` VARCHAR(45) NULL,
  `url_src_img` VARCHAR(250) NOT NULL,
  `url_final_img` VARCHAR(250) NOT NULL,
  `user_id` VARCHAR(50) NOT NULL,
  `gallery_id` INT NULL,
  `created_at` DATETIME NULL,
  `is_approved` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_idx` (`user_id` ASC),
  INDEX `fk_gallery_idx` (`gallery_id` ASC),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `gcpnext16lamp`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gallery`
    FOREIGN KEY (`gallery_id`)
    REFERENCES `gcpnext16lamp`.`gallery` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `gcpnext16lamp`.`votes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gcpnext16lamp`.`votes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(50) NOT NULL,
  `meme_id` INT UNSIGNED NOT NULL,
  `vote` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_votes_user1_idx` (`user_id` ASC),
  INDEX `fk_votes_meme1_idx` (`meme_id` ASC),
  CONSTRAINT `fk_votes_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `gcpnext16lamp`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_votes_meme`
    FOREIGN KEY (`meme_id`)
    REFERENCES `gcpnext16lamp`.`meme` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `gcpnext16lamp`.`appconfig`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gcpnext16lamp`.`appconfig` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `setting_key` VARCHAR(255) NOT NULL,
  `value` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO gcpnext16lamp.gallery VALUES (6,'56cf4f00348e1.png');
INSERT INTO gcpnext16lamp.gallery VALUES (7,'56cf4f32d20a9.png');
INSERT INTO gcpnext16lamp.gallery VALUES (8,'56cf4f3625452.png');
INSERT INTO gcpnext16lamp.gallery VALUES (9,'56cf4f3886fc2.png');
INSERT INTO gcpnext16lamp.gallery VALUES (10,'56cf4f3ab6285.png');
INSERT INTO gcpnext16lamp.gallery VALUES (11,'56cf4f3d3f140.png');
INSERT INTO gcpnext16lamp.gallery VALUES (12,'56cf4f3fdecfa.png');
INSERT INTO gcpnext16lamp.gallery VALUES (13,'56cf4f42579de.png');
INSERT INTO gcpnext16lamp.gallery VALUES (14,'56cf4f44c54bb.png');
INSERT INTO gcpnext16lamp.gallery VALUES (15,'56cf4f476a0d2.png');
INSERT INTO gcpnext16lamp.gallery VALUES (16,'56cf4f4b7793f.png');
INSERT INTO gcpnext16lamp.gallery VALUES (17,'56cf4f4e376f9.png');
INSERT INTO gcpnext16lamp.gallery VALUES (18,'56cf4f50aced9.png');
INSERT INTO gcpnext16lamp.gallery VALUES (19,'56cf4f5352a90.png');
INSERT INTO gcpnext16lamp.gallery VALUES (20,'56cf4f56c4c23.png');
INSERT INTO gcpnext16lamp.gallery VALUES (21,'56cf4f59de781.png');
INSERT INTO gcpnext16lamp.gallery VALUES (22,'56cf4f5ee85b9.png');
INSERT INTO gcpnext16lamp.gallery VALUES (23,'56cf4f66aeafa.png');
INSERT INTO gcpnext16lamp.gallery VALUES (24,'56cf4f6c29463.png');
INSERT INTO gcpnext16lamp.gallery VALUES (25,'56cf4f7083f50.png');
INSERT INTO gcpnext16lamp.gallery VALUES (26,'56cf4f742c27c.png');

INSERT INTO gcpnext16lamp.user(id, name, roles,is_admin, created_at, email) values ('mari','mari',' ', 1,'2016-02-25 13:31:12', 'marianahy@ciandt.com');
INSERT INTO gcpnext16lamp.user(id, name, roles,is_admin, created_at, email) values ('kanjih','kanji hara',' ', 1,'2016-02-25 13:31:12', 'kanjih@ciandt.com');
INSERT INTO gcpnext16lamp.user(id, name, roles,is_admin, created_at, email) values ('gus','Gustavo',' ', 0,'2016-02-25 13:31:12', 'gangelo@ciandt.com');



INSERT INTO gcpnext16lamp.appconfig VALUES (1,'AUTO_APPROVE','0','Flag for meme creation [0 => memes will be pending approval; 1 => meme will be approved automatically]');



CREATE USER 'gcpnext16'@'localhost' IDENTIFIED BY 'abacabbbabebibobu123';

GRANT DELETE ON gcpnext16lamp.* TO 'gcpnext16'@'localhost';
GRANT INSERT ON gcpnext16lamp.* TO 'gcpnext16'@'localhost';
GRANT SELECT ON gcpnext16lamp.* TO 'gcpnext16'@'localhost';
GRANT UPDATE ON gcpnext16lamp.* TO 'gcpnext16'@'localhost';
FLUSH PRIVILEGES;